data "aws_partition" "current" {}
data "aws_caller_identity" "current" {}

locals {
  enabled = length(var.storage_credential_configs) > 0

  storage_bucket_configs = {
    for k, v in var.storage_credential_configs : k => v
    if try(v.create_bucket, false)
  }

  storage_credential_configs_enabled = local.enabled ? var.storage_credential_configs : {}
}

locals {
  bucket_arn_by_key = {
    for k, v in var.storage_credential_configs :
    k => try(module.storage_buckets[k].bucket_arn, "arn:${data.aws_partition.current.partition}:s3:::${v.bucket_name}")
  }

  object_arn_by_key = {
    for k, v in var.storage_credential_configs :
    k => (
      (
        trim(try(v.prefix, "*"), "/") == "" ||
        trim(try(v.prefix, "*"), "/") == "*"
      )
      ? "${local.bucket_arn_by_key[k]}/*"
      : "${local.bucket_arn_by_key[k]}/${trim(v.prefix, "/")}/*"
    )
  }
}

# Step 1: Create one IAM role per storage credential config with minimal initial trust policy
# Note: Each role's trust policy must be updated later (after UC metastore exists)
# to include the external ID generated by `databricks_storage_credential` for that credential.
resource "aws_iam_role" "storage_data_access" {
  for_each = local.storage_credential_configs_enabled

  name = "${var.prefix}-uc-access-${each.key}"
  tags = var.tags

  # Minimal initial trust policy (required by AWS, will be overwritten)
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          AWS = aws_iam_role.unity_catalog_main_role.arn
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  # Ignore changes to assume_role_policy since we'll update it via local-exec
  lifecycle {
    ignore_changes = [assume_role_policy]
  }
}

# Step 2: Create the S3 buckets (optional, per config)
module "storage_buckets" {
  for_each                         = local.enabled ? local.storage_bucket_configs : {}
  source                           = "./storage_bucket"
  bucket_name                      = each.value.bucket_name
  databricks_account_id            = var.databricks_account_id
  tags                             = var.tags
  enable_databricks_account_access = false # We'll use role-based access instead
  allowed_role_arns                = [aws_iam_role.storage_data_access[each.key].arn]
}

# Step 3: Attach S3 access policy to each role (scoped to that bucket/prefix)
data "aws_iam_policy_document" "storage_credential_policy" {
  for_each = local.storage_credential_configs_enabled

  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:GetObjectVersion",
      "s3:GetObjectAcl",
      "s3:GetObjectTagging",
      "s3:PutObject",
      "s3:PutObjectAcl",
      "s3:PutObjectTagging",
      "s3:AbortMultipartUpload",
      "s3:ListMultipartUploadParts",
      "s3:DeleteObject",
      "s3:DeleteObjectTagging"
    ]
    resources = [local.object_arn_by_key[each.key]]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:ListBucket",
      "s3:GetBucketLocation",
      # Needed for multipart upload bookkeeping at the bucket level
      "s3:ListBucketMultipartUploads",
      # Required for Unity Catalog file events (Databricks-managed notifications)
      "s3:GetBucketNotification",
      "s3:PutBucketNotification"
    ]
    resources = [local.bucket_arn_by_key[each.key]]
  }

  statement {
    effect = "Allow"
    actions = [
      "sns:ListSubscriptionsByTopic",
      "sns:GetTopicAttributes",
      "sns:SetTopicAttributes",
      "sns:CreateTopic",
      "sns:TagResource",
      "sns:Publish",
      "sns:Subscribe",
      "sns:Unsubscribe",
      "sns:DeleteTopic",
      "sqs:CreateQueue",
      "sqs:DeleteQueue",
      "sqs:DeleteMessage",
      "sqs:ReceiveMessage",
      "sqs:SendMessage",
      "sqs:GetQueueUrl",
      "sqs:GetQueueAttributes",
      "sqs:SetQueueAttributes",
      "sqs:TagQueue",
      "sqs:ChangeMessageVisibility",
      "sqs:PurgeQueue"
    ]
    resources = [
      "arn:${data.aws_partition.current.partition}:sqs:${var.aws_region}:${data.aws_caller_identity.current.account_id}:*",
      "arn:${data.aws_partition.current.partition}:sns:${var.aws_region}:${data.aws_caller_identity.current.account_id}:*"
    ]
  }

  statement {
    effect = "Allow"
    actions = [
      "sqs:ListQueues",
      "sqs:ListQueueTags",
      "sns:ListTopics"
    ]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "storage_data_access_policy" {
  for_each = local.storage_credential_configs_enabled

  name   = "${var.prefix}-storage-data-access-policy-${each.key}"
  role   = aws_iam_role.storage_data_access[each.key].id
  policy = data.aws_iam_policy_document.storage_credential_policy[each.key].json
}
