locals {
  storage_credential_configs = try(data.terraform_remote_state.infra.outputs.storage_credential_configs, {})
  enabled                    = length(local.storage_credential_configs) > 0

  # Map of role names/arns created in the infra stack for each storage credential key.
  storage_data_access_role_names = try(data.terraform_remote_state.infra.outputs.storage_data_access_role_names, {})
  storage_data_access_role_arns  = try(data.terraform_remote_state.infra.outputs.storage_data_access_role_arns, {})
}

# Create UC storage credentials, after the metastore exists.
resource "databricks_storage_credential" "external" {
  provider       = databricks.mws
  for_each       = local.storage_credential_configs
  force_update   = true
  metastore_id   = module.unity_catalog.metastore_id
  name           = each.value.name
  isolation_mode = "ISOLATION_MODE_ISOLATED"
  comment        = "Managed by TF"

  aws_iam_role {
    role_arn = local.storage_data_access_role_arns[each.key]
  }
}

data "aws_iam_policy_document" "storage_role_trust" {
  for_each = local.enabled ? local.storage_credential_configs : {}

  statement {
    sid     = "Databricks"
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = [var.databricks_uc_master_role_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values = [
        # IMPORTANT: this must be the external ID generated by Databricks for the IAM role assumption,
        # not the Terraform resource ID / storage credential name.
        databricks_storage_credential.external[each.key].aws_iam_role[0].external_id
      ]
    }
  }

  statement {
    sid     = "SelfAssume"
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = [local.storage_data_access_role_arns[each.key]]
    }
  }
}

locals {
  trust_policy_json_by_key = { for k, v in data.aws_iam_policy_document.storage_role_trust : k => v.json }
}

resource "terraform_data" "update_storage_role_trust_policy" {
  for_each = local.enabled ? local.storage_credential_configs : {}

  depends_on = [
    databricks_storage_credential.external
  ]

  provisioner "local-exec" {
    command = <<-EOT
      sleep 5
      aws iam update-assume-role-policy \
        --role-name ${local.storage_data_access_role_names[each.key]} \
        --policy-document '${local.trust_policy_json_by_key[each.key]}'
    EOT
  }

  triggers_replace = [
    local.storage_data_access_role_arns[each.key],
    sha1(local.trust_policy_json_by_key[each.key])
  ]
}

output "storage_credentials" {
  value = {
    for k, sc in databricks_storage_credential.external : k => {
      id   = sc.id
      name = sc.name
    }
  }
  description = "Map of created Databricks storage credentials (keyed by config key)"
}
